### ISSUE TITLE
Problem with GenBank GIs

### ISSUE THREAD

**Issue by trvrb** [blab/nextstrain-db#32]
The command `python vdb/zika_update.py -db vdb -v zika --update_citations` is throwing the error:

```
Connected to the "vdb" database
Updating citation fields
Getting accession numbers for sequences obtained from Genbank
Traceback (most recent call last):
  File "vdb/zika_update.py", line 13, in <module>
    connVDB.update(**args.__dict__)
  File "/Users/trvrb/Dropbox/current-projects/nextstrain-db/vdb/update.py", line 18, in update
    self.update_citations(table=self.sequences_table, **kwargs)
  File "/Users/trvrb/Dropbox/current-projects/nextstrain-db/vdb/update.py", line 28, in update_citations
    _, sequences = self.get_genbank_sequences(**kwargs)
  File "/Users/trvrb/Dropbox/current-projects/nextstrain-db/vdb/update.py", line 47, in get_genbank_sequences
    gi = self.get_GIs(accessions)
  File "/Users/trvrb/Dropbox/current-projects/nextstrain-db/vdb/parse.py", line 194, in get_GIs
    giList = Entrez.read(handle)['IdList']
  File "/usr/local/lib/python2.7/site-packages/Bio/Entrez/__init__.py", line 372, in read
    record = handler.read(handle)
  File "/usr/local/lib/python2.7/site-packages/Bio/Entrez/Parser.py", line 203, in read
    self.parser.ParseFile(handle)
  File "/usr/local/lib/python2.7/site-packages/Bio/Entrez/Parser.py", line 511, in externalEntityRefHandler
    self.dtd_urls.append(url)
UnboundLocalError: local variable 'url' referenced before assignment
```

due to GenBank phasing out GI numbers:

https://www.ncbi.nlm.nih.gov/news/03-02-2016-phase-out-of-GI-numbers/

**Comment by chacalle** [comment]
I don't think this url error is caused by the phasing out of GI numbers. If I try to update one of the Bahia sequences `python vdb/zika_update.py -db vdb -v zika --update_citations --accessions KX101066` I get the same error, when this worked a week or two ago with the same code. I'll try posting a issue to [BioPython](https://github.com/biopython/biopython/issues).

**Comment by chacalle** [comment]
The code to pull genbank files via entrez will have to be updated to use something else besides GIs. But I think this is a separate problem.

**Comment by chacalle** [comment]
I believe this is fixed if you update BioPython to the latest version 1.68.
