### ISSUE TITLE
Issue with flu update groupings

### ISSUE THREAD

**Issue by trvrb** [blab/nextstrain-db#38]
I was just doing an update from GISAID and ran into an error when running:

```
python vdb/flu_update.py -db vdb -v flu --update_groupings
```

I get:

```
Traceback (most recent call last):
  File "vdb/flu_update.py", line 57, in <module>
    connVDB.update(**args.__dict__)
  File "/Users/trvrb/Dropbox/current-projects/nextstrain-db/vdb/update.py", line 22, in update
    self.update_groupings(self.viruses_table, self.sequences_table, **kwargs)
  File "vdb/flu_update.py", line 50, in update_groupings
    self.upload_to_rethinkdb(self.database, self.viruses_table, virus_group, overwrite=True, optimal_upload=optimal_upload)
  File "/Users/trvrb/Dropbox/current-projects/nextstrain-db/vdb/upload.py", line 500, in upload_to_rethinkdb
    raise Exception("Couldn't insert new documents into database", database + "." + table)
Exception: ("Couldn't insert new documents into database", 'vdb.flu_viruses')
```

This is from `upload_to_rethinkdb`: https://github.com/blab/nextstrain-db/blob/master/vdb/upload.py#L484

I just dug around a bit and couldn't see something obvious. @chacalle if you could take a look at your leisure I'd very much appreciate it.

**Comment by chacalle** [comment]
I believe this is fixed now. Also updated the groupings in vdb.

**Comment by trvrb** [comment]
I just confirmed that this is working now. Thanks so much @chacalle! I really appreciate it.
